name: unit-test

on:
  push:
    branches:
      'features/*'

jobs:
 run-unit-test:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout
     uses: actions/checkout@v3.6.0

   - name: run unit test
     run: mvn test
