on:
  push:
    branches:
      - 'features/*'

jobs:
  run-unit-test: # Modified the job name by removing spaces and adding a hyphen
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2 # Updated the version to v2

    - name: Setup Java
      uses: actions/setup-java@v2 # Added a step to set up Java (assuming you need it for Maven)

    - name: Run unit test
      run: mvn test
